// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class discount
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [Required(ErrorMessage = "Description is required")]
    public string description { get; set; }

    [Required(ErrorMessage = "Discount type is required")]
    [StringLength(255)]
    public string discount_type { get; set; }

    [Required(ErrorMessage = "Value is required")]
    [Range(0.01, 100000, ErrorMessage = "Value must be greater than 0")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? value { get; set; }

    [Required(ErrorMessage = "Start date is required")]
    public DateTime? start_date { get; set; }

    [Required(ErrorMessage = "End date is required")]
    public DateTime? end_date { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? minimum_order_amount { get; set; }

    public int? max_uses { get; set; }

    public int? current_uses { get; set; }

    [Required]
    public bool is_active { get; set; }

    public bool is_deleted { get; set; } = false;

    public DateTime? created_at { get; set; } = DateTime.UtcNow;

    public string seller_id { get; set; }
    [ForeignKey("seller_id")]
    public virtual ApplicationUser Seller { get; set; }

    // Navigation property for product discounts **********************************
    public virtual ICollection<product_discount> ProductDiscounts { get; set; }
}