// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class order_item
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string order_id { get; set; }

    [StringLength(255)]
    public string product_id { get; set; }

    public int? quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? unit_price { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? discount_applied { get; set; }
}