// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

[Table("order_history")]
public partial class order_history
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string order_id { get; set; }

    [StringLength(255)]
    public string status { get; set; }

    [StringLength(255)]
    public string changed_by { get; set; }

    public DateTime? changed_at { get; set; }

    public string notes { get; set; }
}