// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class product
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? price { get; set; }

    [StringLength(255)]
    public string Brand { get; set; }

    [StringLength(255)]
    public string Colors { get; set; }

    [StringLength(255)]
    public string Sizes { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? discount_price { get; set; }

    public int? stock_quantity { get; set; }

    [StringLength(255)]
    public string sku { get; set; }

    [StringLength(255)]
    public string category_id { get; set; }

    public string seller_id { get; set; }
    [ForeignKey("seller_id")]
    public virtual ApplicationUser Seller { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;

    public DateTime? last_modified_at { get; set; }

    public bool? is_active { get; set; }

    public bool? is_approved { get; set; }

    [StringLength(255)]
    public string approved_by { get; set; }

    public DateTime? approved_at { get; set; }

    public bool is_deleted { get; set; } = false;
    
}